# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from motor_sc/sens9ax.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class sens9ax(genpy.Message):
  _md5sum = "ae05447afd7568f477683a6ee9035588"
  _type = "motor_sc/sens9ax"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """uint8 ID
uint64 timestamp
float64[3] compass
float64[3] gyro
float64[3] accel
float64[3] fusionPose
float64[4] fusionQPose
"""
  __slots__ = ['ID','timestamp','compass','gyro','accel','fusionPose','fusionQPose']
  _slot_types = ['uint8','uint64','float64[3]','float64[3]','float64[3]','float64[3]','float64[4]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       ID,timestamp,compass,gyro,accel,fusionPose,fusionQPose

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(sens9ax, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.ID is None:
        self.ID = 0
      if self.timestamp is None:
        self.timestamp = 0
      if self.compass is None:
        self.compass = [0.] * 3
      if self.gyro is None:
        self.gyro = [0.] * 3
      if self.accel is None:
        self.accel = [0.] * 3
      if self.fusionPose is None:
        self.fusionPose = [0.] * 3
      if self.fusionQPose is None:
        self.fusionQPose = [0.] * 4
    else:
      self.ID = 0
      self.timestamp = 0
      self.compass = [0.] * 3
      self.gyro = [0.] * 3
      self.accel = [0.] * 3
      self.fusionPose = [0.] * 3
      self.fusionQPose = [0.] * 4

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_BQ().pack(_x.ID, _x.timestamp))
      buff.write(_get_struct_3d().pack(*self.compass))
      buff.write(_get_struct_3d().pack(*self.gyro))
      buff.write(_get_struct_3d().pack(*self.accel))
      buff.write(_get_struct_3d().pack(*self.fusionPose))
      buff.write(_get_struct_4d().pack(*self.fusionQPose))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 9
      (_x.ID, _x.timestamp,) = _get_struct_BQ().unpack(str[start:end])
      start = end
      end += 24
      self.compass = _get_struct_3d().unpack(str[start:end])
      start = end
      end += 24
      self.gyro = _get_struct_3d().unpack(str[start:end])
      start = end
      end += 24
      self.accel = _get_struct_3d().unpack(str[start:end])
      start = end
      end += 24
      self.fusionPose = _get_struct_3d().unpack(str[start:end])
      start = end
      end += 32
      self.fusionQPose = _get_struct_4d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_BQ().pack(_x.ID, _x.timestamp))
      buff.write(self.compass.tostring())
      buff.write(self.gyro.tostring())
      buff.write(self.accel.tostring())
      buff.write(self.fusionPose.tostring())
      buff.write(self.fusionQPose.tostring())
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 9
      (_x.ID, _x.timestamp,) = _get_struct_BQ().unpack(str[start:end])
      start = end
      end += 24
      self.compass = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=3)
      start = end
      end += 24
      self.gyro = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=3)
      start = end
      end += 24
      self.accel = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=3)
      start = end
      end += 24
      self.fusionPose = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=3)
      start = end
      end += 32
      self.fusionQPose = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=4)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_4d = None
def _get_struct_4d():
    global _struct_4d
    if _struct_4d is None:
        _struct_4d = struct.Struct("<4d")
    return _struct_4d
_struct_BQ = None
def _get_struct_BQ():
    global _struct_BQ
    if _struct_BQ is None:
        _struct_BQ = struct.Struct("<BQ")
    return _struct_BQ
_struct_3d = None
def _get_struct_3d():
    global _struct_3d
    if _struct_3d is None:
        _struct_3d = struct.Struct("<3d")
    return _struct_3d
