// Generated by gencpp from file motor_sc/g_sens.msg
// DO NOT EDIT!


#ifndef MOTOR_SC_MESSAGE_G_SENS_H
#define MOTOR_SC_MESSAGE_G_SENS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <motor_sc/sens9ax.h>
#include <motor_sc/sens9ax.h>

namespace motor_sc
{
template <class ContainerAllocator>
struct g_sens_
{
  typedef g_sens_<ContainerAllocator> Type;

  g_sens_()
    : Front_sens()
    , Rear_sens()  {
    }
  g_sens_(const ContainerAllocator& _alloc)
    : Front_sens(_alloc)
    , Rear_sens(_alloc)  {
  (void)_alloc;
    }



   typedef  ::motor_sc::sens9ax_<ContainerAllocator>  _Front_sens_type;
  _Front_sens_type Front_sens;

   typedef  ::motor_sc::sens9ax_<ContainerAllocator>  _Rear_sens_type;
  _Rear_sens_type Rear_sens;




  typedef boost::shared_ptr< ::motor_sc::g_sens_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::motor_sc::g_sens_<ContainerAllocator> const> ConstPtr;

}; // struct g_sens_

typedef ::motor_sc::g_sens_<std::allocator<void> > g_sens;

typedef boost::shared_ptr< ::motor_sc::g_sens > g_sensPtr;
typedef boost::shared_ptr< ::motor_sc::g_sens const> g_sensConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::motor_sc::g_sens_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::motor_sc::g_sens_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace motor_sc

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'motor_sc': ['/home/rctvrc/catkin_workspace/src/motor_sc/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::motor_sc::g_sens_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::motor_sc::g_sens_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::motor_sc::g_sens_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::motor_sc::g_sens_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::motor_sc::g_sens_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::motor_sc::g_sens_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::motor_sc::g_sens_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2ba48ff788ab0557badb810806e50757";
  }

  static const char* value(const ::motor_sc::g_sens_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2ba48ff788ab0557ULL;
  static const uint64_t static_value2 = 0xbadb810806e50757ULL;
};

template<class ContainerAllocator>
struct DataType< ::motor_sc::g_sens_<ContainerAllocator> >
{
  static const char* value()
  {
    return "motor_sc/g_sens";
  }

  static const char* value(const ::motor_sc::g_sens_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::motor_sc::g_sens_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sens9ax Front_sens\n\
sens9ax Rear_sens\n\
================================================================================\n\
MSG: motor_sc/sens9ax\n\
uint8 ID\n\
uint64 timestamp\n\
float64[3] compass\n\
float64[3] gyro\n\
float64[3] accel\n\
float64[3] fusionPose\n\
float64[4] fusionQPose\n\
";
  }

  static const char* value(const ::motor_sc::g_sens_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::motor_sc::g_sens_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.Front_sens);
      stream.next(m.Rear_sens);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct g_sens_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::motor_sc::g_sens_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::motor_sc::g_sens_<ContainerAllocator>& v)
  {
    s << indent << "Front_sens: ";
    s << std::endl;
    Printer< ::motor_sc::sens9ax_<ContainerAllocator> >::stream(s, indent + "  ", v.Front_sens);
    s << indent << "Rear_sens: ";
    s << std::endl;
    Printer< ::motor_sc::sens9ax_<ContainerAllocator> >::stream(s, indent + "  ", v.Rear_sens);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOTOR_SC_MESSAGE_G_SENS_H
