// Generated by gencpp from file motor_sc/LED_controll.msg
// DO NOT EDIT!


#ifndef MOTOR_SC_MESSAGE_LED_CONTROLL_H
#define MOTOR_SC_MESSAGE_LED_CONTROLL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace motor_sc
{
template <class ContainerAllocator>
struct LED_controll_
{
  typedef LED_controll_<ContainerAllocator> Type;

  LED_controll_()
    : LED_ID(0)
    , RGB()  {
      RGB.assign(0);
  }
  LED_controll_(const ContainerAllocator& _alloc)
    : LED_ID(0)
    , RGB()  {
  (void)_alloc;
      RGB.assign(0);
  }



   typedef uint8_t _LED_ID_type;
  _LED_ID_type LED_ID;

   typedef boost::array<uint8_t, 3>  _RGB_type;
  _RGB_type RGB;




  typedef boost::shared_ptr< ::motor_sc::LED_controll_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::motor_sc::LED_controll_<ContainerAllocator> const> ConstPtr;

}; // struct LED_controll_

typedef ::motor_sc::LED_controll_<std::allocator<void> > LED_controll;

typedef boost::shared_ptr< ::motor_sc::LED_controll > LED_controllPtr;
typedef boost::shared_ptr< ::motor_sc::LED_controll const> LED_controllConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::motor_sc::LED_controll_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::motor_sc::LED_controll_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace motor_sc

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'motor_sc': ['/home/rctvrc/catkin_workspace/src/motor_sc/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::motor_sc::LED_controll_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::motor_sc::LED_controll_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::motor_sc::LED_controll_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::motor_sc::LED_controll_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::motor_sc::LED_controll_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::motor_sc::LED_controll_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::motor_sc::LED_controll_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7863f5ba3af370bb462fe9903dbd7387";
  }

  static const char* value(const ::motor_sc::LED_controll_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7863f5ba3af370bbULL;
  static const uint64_t static_value2 = 0x462fe9903dbd7387ULL;
};

template<class ContainerAllocator>
struct DataType< ::motor_sc::LED_controll_<ContainerAllocator> >
{
  static const char* value()
  {
    return "motor_sc/LED_controll";
  }

  static const char* value(const ::motor_sc::LED_controll_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::motor_sc::LED_controll_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 LED_ID \n\
uint8[3] RGB\n\
";
  }

  static const char* value(const ::motor_sc::LED_controll_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::motor_sc::LED_controll_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.LED_ID);
      stream.next(m.RGB);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LED_controll_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::motor_sc::LED_controll_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::motor_sc::LED_controll_<ContainerAllocator>& v)
  {
    s << indent << "LED_ID: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.LED_ID);
    s << indent << "RGB[]" << std::endl;
    for (size_t i = 0; i < v.RGB.size(); ++i)
    {
      s << indent << "  RGB[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.RGB[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOTOR_SC_MESSAGE_LED_CONTROLL_H
