// Generated by gencpp from file motor_sc/minf_msg.msg
// DO NOT EDIT!


#ifndef MOTOR_SC_MESSAGE_MINF_MSG_H
#define MOTOR_SC_MESSAGE_MINF_MSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace motor_sc
{
template <class ContainerAllocator>
struct minf_msg_
{
  typedef minf_msg_<ContainerAllocator> Type;

  minf_msg_()
    : ID(0)
    , CURRENT(0.0)
    , RPM(0.0)  {
    }
  minf_msg_(const ContainerAllocator& _alloc)
    : ID(0)
    , CURRENT(0.0)
    , RPM(0.0)  {
  (void)_alloc;
    }



   typedef uint8_t _ID_type;
  _ID_type ID;

   typedef float _CURRENT_type;
  _CURRENT_type CURRENT;

   typedef float _RPM_type;
  _RPM_type RPM;




  typedef boost::shared_ptr< ::motor_sc::minf_msg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::motor_sc::minf_msg_<ContainerAllocator> const> ConstPtr;

}; // struct minf_msg_

typedef ::motor_sc::minf_msg_<std::allocator<void> > minf_msg;

typedef boost::shared_ptr< ::motor_sc::minf_msg > minf_msgPtr;
typedef boost::shared_ptr< ::motor_sc::minf_msg const> minf_msgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::motor_sc::minf_msg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::motor_sc::minf_msg_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace motor_sc

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'motor_sc': ['/home/rctvrc/catkin_workspace/src/motor_sc/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::motor_sc::minf_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::motor_sc::minf_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::motor_sc::minf_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::motor_sc::minf_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::motor_sc::minf_msg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::motor_sc::minf_msg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::motor_sc::minf_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b85c91d3c46d01d1f24f2a77e165b6ca";
  }

  static const char* value(const ::motor_sc::minf_msg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb85c91d3c46d01d1ULL;
  static const uint64_t static_value2 = 0xf24f2a77e165b6caULL;
};

template<class ContainerAllocator>
struct DataType< ::motor_sc::minf_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "motor_sc/minf_msg";
  }

  static const char* value(const ::motor_sc::minf_msg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::motor_sc::minf_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 ID\n\
float32 CURRENT\n\
float32 RPM\n\
";
  }

  static const char* value(const ::motor_sc::minf_msg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::motor_sc::minf_msg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.ID);
      stream.next(m.CURRENT);
      stream.next(m.RPM);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct minf_msg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::motor_sc::minf_msg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::motor_sc::minf_msg_<ContainerAllocator>& v)
  {
    s << indent << "ID: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.ID);
    s << indent << "CURRENT: ";
    Printer<float>::stream(s, indent + "  ", v.CURRENT);
    s << indent << "RPM: ";
    Printer<float>::stream(s, indent + "  ", v.RPM);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOTOR_SC_MESSAGE_MINF_MSG_H
