// Generated by gencpp from file motor_sc/motors_feedback.msg
// DO NOT EDIT!


#ifndef MOTOR_SC_MESSAGE_MOTORS_FEEDBACK_H
#define MOTOR_SC_MESSAGE_MOTORS_FEEDBACK_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace motor_sc
{
template <class ContainerAllocator>
struct motors_feedback_
{
  typedef motors_feedback_<ContainerAllocator> Type;

  motors_feedback_()
    : ID(0)
    , CUR()
    , RPM()  {
      CUR.assign(0.0);

      RPM.assign(0.0);
  }
  motors_feedback_(const ContainerAllocator& _alloc)
    : ID(0)
    , CUR()
    , RPM()  {
  (void)_alloc;
      CUR.assign(0.0);

      RPM.assign(0.0);
  }



   typedef uint8_t _ID_type;
  _ID_type ID;

   typedef boost::array<float, 4>  _CUR_type;
  _CUR_type CUR;

   typedef boost::array<float, 4>  _RPM_type;
  _RPM_type RPM;




  typedef boost::shared_ptr< ::motor_sc::motors_feedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::motor_sc::motors_feedback_<ContainerAllocator> const> ConstPtr;

}; // struct motors_feedback_

typedef ::motor_sc::motors_feedback_<std::allocator<void> > motors_feedback;

typedef boost::shared_ptr< ::motor_sc::motors_feedback > motors_feedbackPtr;
typedef boost::shared_ptr< ::motor_sc::motors_feedback const> motors_feedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::motor_sc::motors_feedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::motor_sc::motors_feedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace motor_sc

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'motor_sc': ['/home/rctvrc/catkin_workspace/src/motor_sc/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::motor_sc::motors_feedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::motor_sc::motors_feedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::motor_sc::motors_feedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::motor_sc::motors_feedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::motor_sc::motors_feedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::motor_sc::motors_feedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::motor_sc::motors_feedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "94194bc441d86cf5551f8c0ed1c128f4";
  }

  static const char* value(const ::motor_sc::motors_feedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x94194bc441d86cf5ULL;
  static const uint64_t static_value2 = 0x551f8c0ed1c128f4ULL;
};

template<class ContainerAllocator>
struct DataType< ::motor_sc::motors_feedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "motor_sc/motors_feedback";
  }

  static const char* value(const ::motor_sc::motors_feedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::motor_sc::motors_feedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 ID\n\
float32[4] CUR\n\
float32[4] RPM\n\
";
  }

  static const char* value(const ::motor_sc::motors_feedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::motor_sc::motors_feedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.ID);
      stream.next(m.CUR);
      stream.next(m.RPM);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct motors_feedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::motor_sc::motors_feedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::motor_sc::motors_feedback_<ContainerAllocator>& v)
  {
    s << indent << "ID: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.ID);
    s << indent << "CUR[]" << std::endl;
    for (size_t i = 0; i < v.CUR.size(); ++i)
    {
      s << indent << "  CUR[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.CUR[i]);
    }
    s << indent << "RPM[]" << std::endl;
    for (size_t i = 0; i < v.RPM.size(); ++i)
    {
      s << indent << "  RPM[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.RPM[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOTOR_SC_MESSAGE_MOTORS_FEEDBACK_H
