classdef mcnt_msg < robotics.ros.Message
    %mcnt_msg MATLAB implementation of motor_sc/mcnt_msg
    %   This class was automatically generated by
    %   robotics.ros.msg.internal.gen.MessageClassGenerator.
    
    %   Copyright 2014-2018 The MathWorks, Inc.
    
    %#ok<*INUSD>
    
    properties (Constant)
        MessageType = 'motor_sc/mcnt_msg' % The ROS message type
    end
    
    properties (Constant, Hidden)
        MD5Checksum = '8f8d9d38dc81575a88dd6f44006cd842' % The MD5 Checksum of the message definition
    end
    
    properties (Access = protected)
        JavaMessage % The Java message object
    end
    
    properties (Dependent)
        ID
        CntData
    end
    
    properties (Constant, Hidden)
        PropertyList = {'CntData', 'ID'} % List of non-constant message properties
        ROSPropertyList = {'cnt_data', 'ID'} % List of non-constant ROS message properties
    end
    
    methods
        function obj = mcnt_msg(msg)
            %mcnt_msg Construct the message object mcnt_msg
            import com.mathworks.toolbox.robotics.ros.message.MessageInfo;
            
            % Support default constructor
            if nargin == 0
                obj.JavaMessage = obj.createNewJavaMessage;
                return;
            end
            
            % Construct appropriate empty array
            if isempty(msg)
                obj = obj.empty(0,1);
                return;
            end
            
            % Make scalar construction fast
            if isscalar(msg)
                % Check for correct input class
                if ~MessageInfo.compareTypes(msg(1), obj.MessageType)
                    error(message('robotics:ros:message:NoTypeMatch', obj.MessageType, ...
                        char(MessageInfo.getType(msg(1))) ));
                end
                obj.JavaMessage = msg(1);
                return;
            end
            
            % Check that this is a vector of scalar messages. Since this
            % is an object array, use arrayfun to verify.
            if ~all(arrayfun(@isscalar, msg))
                error(message('robotics:ros:message:MessageArraySizeError'));
            end
            
            % Check that all messages in the array have the correct type
            if ~all(arrayfun(@(x) MessageInfo.compareTypes(x, obj.MessageType), msg))
                error(message('robotics:ros:message:NoTypeMatchArray', obj.MessageType));
            end
            
            % Construct array of objects if necessary
            objType = class(obj);
            for i = 1:length(msg)
                obj(i,1) = feval(objType, msg(i)); %#ok<AGROW>
            end
        end
        
        function id = get.ID(obj)
            %get.ID Get the value for property ID
            id = typecast(int8(obj.JavaMessage.getID), 'uint8');
        end
        
        function set.ID(obj, id)
            %set.ID Set the value for property ID
            validateattributes(id, {'numeric'}, {'nonempty', 'scalar'}, 'mcnt_msg', 'ID');
            
            obj.JavaMessage.setID(id);
        end
        
        function cntdata = get.CntData(obj)
            %get.CntData Get the value for property CntData
            javaArray = obj.JavaMessage.getCntData;
            array = obj.readJavaArray(javaArray, 'uint8');
            cntdata = uint8(array);
        end
        
        function set.CntData(obj, cntdata)
            %set.CntData Set the value for property CntData
            validateattributes(cntdata, {'numeric'}, {'vector', 'numel', 2}, 'mcnt_msg', 'CntData');
            
            javaArray = obj.JavaMessage.getCntData;
            array = obj.writeJavaArray(cntdata, javaArray, 'uint8');
            obj.JavaMessage.setCntData(array);
        end
    end
    
    methods (Access = protected)
        function cpObj = copyElement(obj)
            %copyElement Implements deep copy behavior for message
            
            % Call default copy method for shallow copy
            cpObj = copyElement@robotics.ros.Message(obj);
            
            % Create a new Java message object
            cpObj.JavaMessage = obj.createNewJavaMessage;
            
            % Iterate over all primitive properties
            cpObj.ID = obj.ID;
            cpObj.CntData = obj.CntData;
        end
        
        function reload(obj, strObj)
            %reload Called by loadobj to assign properties
            obj.ID = strObj.ID;
            obj.CntData = strObj.CntData;
        end
    end
    
    methods (Access = ?robotics.ros.Message)
        function strObj = saveobj(obj)
            %saveobj Implements saving of message to MAT file
            
            % Return an empty element if object array is empty
            if isempty(obj)
                strObj = struct.empty;
                return
            end
            
            strObj.ID = obj.ID;
            strObj.CntData = obj.CntData;
        end
    end
    
    methods (Static, Access = {?matlab.unittest.TestCase, ?robotics.ros.Message})
        function obj = loadobj(strObj)
            %loadobj Implements loading of message from MAT file
            
            % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = robotics.ros.custom.msggen.motor_sc.mcnt_msg.empty(0,1);
                return
            end
            
            % Create an empty message object
            obj = robotics.ros.custom.msggen.motor_sc.mcnt_msg;
            obj.reload(strObj);
        end
    end
end
