classdef minf_msg < robotics.ros.Message
    %minf_msg MATLAB implementation of motor_sc/minf_msg
    %   This class was automatically generated by
    %   robotics.ros.msg.internal.gen.MessageClassGenerator.
    
    %   Copyright 2014-2018 The MathWorks, Inc.
    
    %#ok<*INUSD>
    
    properties (Constant)
        MessageType = 'motor_sc/minf_msg' % The ROS message type
    end
    
    properties (Constant, Hidden)
        MD5Checksum = 'b85c91d3c46d01d1f24f2a77e165b6ca' % The MD5 Checksum of the message definition
    end
    
    properties (Access = protected)
        JavaMessage % The Java message object
    end
    
    properties (Dependent)
        ID
        CURRENT
        RPM
    end
    
    properties (Constant, Hidden)
        PropertyList = {'CURRENT', 'ID', 'RPM'} % List of non-constant message properties
        ROSPropertyList = {'CURRENT', 'ID', 'RPM'} % List of non-constant ROS message properties
    end
    
    methods
        function obj = minf_msg(msg)
            %minf_msg Construct the message object minf_msg
            import com.mathworks.toolbox.robotics.ros.message.MessageInfo;
            
            % Support default constructor
            if nargin == 0
                obj.JavaMessage = obj.createNewJavaMessage;
                return;
            end
            
            % Construct appropriate empty array
            if isempty(msg)
                obj = obj.empty(0,1);
                return;
            end
            
            % Make scalar construction fast
            if isscalar(msg)
                % Check for correct input class
                if ~MessageInfo.compareTypes(msg(1), obj.MessageType)
                    error(message('robotics:ros:message:NoTypeMatch', obj.MessageType, ...
                        char(MessageInfo.getType(msg(1))) ));
                end
                obj.JavaMessage = msg(1);
                return;
            end
            
            % Check that this is a vector of scalar messages. Since this
            % is an object array, use arrayfun to verify.
            if ~all(arrayfun(@isscalar, msg))
                error(message('robotics:ros:message:MessageArraySizeError'));
            end
            
            % Check that all messages in the array have the correct type
            if ~all(arrayfun(@(x) MessageInfo.compareTypes(x, obj.MessageType), msg))
                error(message('robotics:ros:message:NoTypeMatchArray', obj.MessageType));
            end
            
            % Construct array of objects if necessary
            objType = class(obj);
            for i = 1:length(msg)
                obj(i,1) = feval(objType, msg(i)); %#ok<AGROW>
            end
        end
        
        function id = get.ID(obj)
            %get.ID Get the value for property ID
            id = typecast(int8(obj.JavaMessage.getID), 'uint8');
        end
        
        function set.ID(obj, id)
            %set.ID Set the value for property ID
            validateattributes(id, {'numeric'}, {'nonempty', 'scalar'}, 'minf_msg', 'ID');
            
            obj.JavaMessage.setID(id);
        end
        
        function current = get.CURRENT(obj)
            %get.CURRENT Get the value for property CURRENT
            current = single(obj.JavaMessage.getCURRENT);
        end
        
        function set.CURRENT(obj, current)
            %set.CURRENT Set the value for property CURRENT
            validateattributes(current, {'numeric'}, {'nonempty', 'scalar'}, 'minf_msg', 'CURRENT');
            
            obj.JavaMessage.setCURRENT(current);
        end
        
        function rpm = get.RPM(obj)
            %get.RPM Get the value for property RPM
            rpm = single(obj.JavaMessage.getRPM);
        end
        
        function set.RPM(obj, rpm)
            %set.RPM Set the value for property RPM
            validateattributes(rpm, {'numeric'}, {'nonempty', 'scalar'}, 'minf_msg', 'RPM');
            
            obj.JavaMessage.setRPM(rpm);
        end
    end
    
    methods (Access = protected)
        function cpObj = copyElement(obj)
            %copyElement Implements deep copy behavior for message
            
            % Call default copy method for shallow copy
            cpObj = copyElement@robotics.ros.Message(obj);
            
            % Create a new Java message object
            cpObj.JavaMessage = obj.createNewJavaMessage;
            
            % Iterate over all primitive properties
            cpObj.ID = obj.ID;
            cpObj.CURRENT = obj.CURRENT;
            cpObj.RPM = obj.RPM;
        end
        
        function reload(obj, strObj)
            %reload Called by loadobj to assign properties
            obj.ID = strObj.ID;
            obj.CURRENT = strObj.CURRENT;
            obj.RPM = strObj.RPM;
        end
    end
    
    methods (Access = ?robotics.ros.Message)
        function strObj = saveobj(obj)
            %saveobj Implements saving of message to MAT file
            
            % Return an empty element if object array is empty
            if isempty(obj)
                strObj = struct.empty;
                return
            end
            
            strObj.ID = obj.ID;
            strObj.CURRENT = obj.CURRENT;
            strObj.RPM = obj.RPM;
        end
    end
    
    methods (Static, Access = {?matlab.unittest.TestCase, ?robotics.ros.Message})
        function obj = loadobj(strObj)
            %loadobj Implements loading of message from MAT file
            
            % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = robotics.ros.custom.msggen.motor_sc.minf_msg.empty(0,1);
                return
            end
            
            % Create an empty message object
            obj = robotics.ros.custom.msggen.motor_sc.minf_msg;
            obj.reload(strObj);
        end
    end
end
